name: Build and Push Docker Images

on:
  push:
    branches:
      - main                    
  workflow_dispatch:            

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build-node:
    name: Build Node.js App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push Node image
        uses: docker/build-push-action@v5
        with:
          context: ./super-app/node
          file: ./super-app/node/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/super-app-node:latest
            ${{ env.DOCKERHUB_USERNAME }}/super-app-node:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # Job 2: Сборка и публикация PHP
  build-php:
    name: Build PHP App
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push PHP image
        uses: docker/build-push-action@v5
        with:
          context: ./super-app/php
          file: ./super-app/php/Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USERNAME }}/super-app-php:latest
            ${{ env.DOCKERHUB_USERNAME }}/super-app-php:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
